package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChange<M extends BaseChange<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}

	public java.lang.Integer getUid() {
		return get("uid");
	}

	public void setDid(java.lang.Integer did) {
		set("did", did);
	}

	public java.lang.Integer getDid() {
		return get("did");
	}

	public void setLid(java.lang.Integer lid) {
		set("lid", lid);
	}

	public java.lang.Integer getLid() {
		return get("lid");
	}

	public void setFid(java.lang.Integer fid) {
		set("fid", fid);
	}

	public java.lang.Integer getFid() {
		return get("fid");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setReasonBefore(java.lang.String reasonBefore) {
		set("reasonBefore", reasonBefore);
	}

	public java.lang.String getReasonBefore() {
		return get("reasonBefore");
	}

	public void setReasonAfter(java.lang.String reasonAfter) {
		set("reasonAfter", reasonAfter);
	}

	public java.lang.String getReasonAfter() {
		return get("reasonAfter");
	}

	public void setTypeBefore(java.lang.String typeBefore) {
		set("typeBefore", typeBefore);
	}

	public java.lang.String getTypeBefore() {
		return get("typeBefore");
	}

	public void setTypeAfter(java.lang.String typeAfter) {
		set("typeAfter", typeAfter);
	}

	public java.lang.String getTypeAfter() {
		return get("typeAfter");
	}

	public void setDirectBefore(java.lang.String directBefore) {
		set("directBefore", directBefore);
	}

	public java.lang.String getDirectBefore() {
		return get("directBefore");
	}

	public void setDirectAfter(java.lang.String directAfter) {
		set("directAfter", directAfter);
	}

	public java.lang.String getDirectAfter() {
		return get("directAfter");
	}

	public void setRemarkBefore(java.lang.String remarkBefore) {
		set("remarkBefore", remarkBefore);
	}

	public java.lang.String getRemarkBefore() {
		return get("remarkBefore");
	}

	public void setRemarkAfter(java.lang.String remarkAfter) {
		set("remarkAfter", remarkAfter);
	}

	public java.lang.String getRemarkAfter() {
		return get("remarkAfter");
	}

}
