package com.wts.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChange<M extends BaseChange<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setPid(Integer pid) {
		set("pid", pid);
	}

	public Integer getPid() {
		return get("pid");
	}

	public void setDid(Integer did) {
		set("did", did);
	}

	public Integer getDid() {
		return get("did");
	}

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() {
		return get("uid");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setNameBefore(String nameBefore) {
		set("nameBefore", nameBefore);
	}

	public String getNameBefore() {
		return get("nameBefore");
	}

	public void setNameAfter(String nameAfter) {
		set("nameAfter", nameAfter);
	}

	public String getNameAfter() {
		return get("nameAfter");
	}

	public void setNumberBefore(String numberBefore) {
		set("numberBefore", numberBefore);
	}

	public String getNumberBefore() {
		return get("numberBefore");
	}

	public void setNumberAfter(String numberAfter) {
		set("numberAfter", numberAfter);
	}

	public String getNumberAfter() {
		return get("numberAfter");
	}

	public void setPhone1Before(String phone1Before) {
		set("phone1Before", phone1Before);
	}

	public String getPhone1Before() {
		return get("phone1Before");
	}

	public void setPhone1After(String phone1After) {
		set("phone1After", phone1After);
	}

	public String getPhone1After() {
		return get("phone1After");
	}

	public void setPhone2Before(String phone2Before) {
		set("phone2Before", phone2Before);
	}

	public String getPhone2Before() {
		return get("phone2Before");
	}

	public void setPhone2After(String phone2After) {
		set("phone2After", phone2After);
	}

	public String getPhone2After() {
		return get("phone2After");
	}

	public void setAddressBefore(String addressBefore) {
		set("addressBefore", addressBefore);
	}

	public String getAddressBefore() {
		return get("addressBefore");
	}

	public void setAddressAfter(String addressAfter) {
		set("addressAfter", addressAfter);
	}

	public String getAddressAfter() {
		return get("addressAfter");
	}

	public void setFileAgeBefore(java.util.Date fileAgeBefore) {
		set("fileAgeBefore", fileAgeBefore);
	}

	public java.util.Date getFileAgeBefore() {
		return get("fileAgeBefore");
	}

	public void setFileAgeAfter(java.util.Date fileAgeAfter) {
		set("fileAgeAfter", fileAgeAfter);
	}

	public java.util.Date getFileAgeAfter() {
		return get("fileAgeAfter");
	}

}
