package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePolity<M extends BasePolity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}

	public java.lang.Integer getUid() {
		return get("uid");
	}

	public void setFid(java.lang.Integer fid) {
		set("fid", fid);
	}

	public java.lang.Integer getFid() {
		return get("fid");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setNation(java.lang.String nation) {
		set("nation", nation);
	}

	public java.lang.String getNation() {
		return get("nation");
	}

	public void setLearn(java.lang.String learn) {
		set("learn", learn);
	}

	public java.lang.String getLearn() {
		return get("learn");
	}

	public void setLeave(java.lang.String leave) {
		set("leave", leave);
	}

	public java.lang.String getLeave() {
		return get("leave");
	}

	public void setFace(java.lang.String face) {
		set("face", face);
	}

	public java.lang.String getFace() {
		return get("face");
	}

	public void setWork(java.lang.String work) {
		set("work", work);
	}

	public java.lang.String getWork() {
		return get("work");
	}

	public void setZl(java.lang.String zl) {
		set("zl", zl);
	}

	public java.lang.String getZl() {
		return get("zl");
	}

	public void setWg(java.lang.String wg) {
		set("wg", wg);
	}

	public java.lang.String getWg() {
		return get("wg");
	}

	public void setLs(java.lang.String ls) {
		set("ls", ls);
	}

	public java.lang.String getLs() {
		return get("ls");
	}

	public void setFl(java.lang.String fl) {
		set("fl", fl);
	}

	public java.lang.String getFl() {
		return get("fl");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
