package com.wts.entity.model;

import com.wts.entity.base.BaseChange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Change extends BaseChange<Change> {
	public static final Change dao = new Change();

}
