package com.wts.entity.model;

import com.wts.entity.base.BaseExport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Export extends BaseExport<Export> {
	public static final Export dao = new Export();
}
