package com.wts.entity.model;

import com.wts.entity.base.BaseExtract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Extract extends BaseExtract<Extract> {
	public static final Extract dao = new Extract();
}
