package com.wts.entity.model;

import com.wts.entity.base.BaseLogin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Login extends BaseLogin<Login> {
	public static final Login dao = new Login();

}
