package com.wts.entity.model;

import com.wts.entity.base.BaseLook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Look extends BaseLook<Look> {
	public static final Look dao = new Look();
}
