package com.wts.entity.model;

import com.jfinal.plugin.activerecord.Page;
import com.wts.entity.base.BasePerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Person extends BasePerson<Person> {
	public static final Person dao = new Person();

	public Page<Person> paginate2(int pageNumber, int pageSize, String personName, String personNumber, String personState) {
		return paginate(pageNumber, pageSize, "SELECT * ",
							"FROM person WHERE name LIKE '%" + personName + "%' AND number LIKE '%" + personNumber + "%'  AND state LIKE '%" + personState + "%' ORDER BY id DESC");

	}
}
