package com.wts.entity.model;

import com.wts.entity.base.BasePolity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Polity extends BasePolity<Polity> {
	public static final Polity dao = new Polity();
}
