package com.wts.entity.model;

import com.wts.entity.base.BasePrint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Print extends BasePrint<Print> {
	public static final Print dao = new Print();

}
