package com.wts.entity.model;

import com.wts.entity.base.BaseProve;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Prove extends BaseProve<Prove> {
	public static final Prove dao = new Prove();
}
