package com.wts.entity.model;

import com.wts.entity.base.BaseTrans;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Trans extends BaseTrans<Trans> {
	public static final Trans dao = new Trans();
}
