package com.wts.entity.model;

import com.wts.entity.base.BaseVariantu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Variantu extends BaseVariantu<Variantu> {
	public static final Variantu dao = new Variantu();
}
