package com.wts.entity.model;

import com.wts.entity.base.BaseVariantd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Variantd extends BaseVariantd<Variantd> {
	public static final Variantd dao = new Variantd();
}
