package com.wts.entity.model;

import com.wts.entity.base.BaseVariantp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Variantp extends BaseVariantp<Variantp> {
	public static final Variantp dao = new Variantp();
}
