package com.wts.common.model;

import com.wts.common.model.base.BaseFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Flow extends BaseFlow<Flow> {
	public static final Flow dao = new Flow();
}
