package com.wts.common.model;

import com.wts.common.model.base.BasePerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Person extends BasePerson<Person> {
	public static final Person dao = new Person();
}
