package com.wts.common.model;

import com.wts.common.model.base.BaseTrans;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Trans extends BaseTrans<Trans> {
	public static final Trans dao = new Trans();
}
